# Gruvbox
[colors]
foreground = "#ebdbb2"
background = "#282828"
cursor_bg = "#8ec07c"
cursor_border = "#8ec07c"
cursor_fg = "#282828"
selection_bg = "#e6d4a3"
selection_fg = "#534a42"



ansi = ["#282828", "#cc241d", "#b8bb26", "#fabd2f", "#83a598", "#d3869b", "#8ec07c", "#ebdbb2"]
brights = ["#98971a", "#d79921", "#458588", "#b16286", "#689d6a", "#a89984", "#928374", "#fb4934"]

[[tab_bar]]
background = "#282828"
active_tab.bg_color = "#8ec07c"
